### PR TITLE
Right-align USD column

### PR DESCRIPTION
**Pull request by alkum**
Right align numerical values, to make it easier for team leads to review amounts.

### CODE REVIEW

**Review by ripcurlx — APPROVED** [review]
utACK

**Comment by ripcurlx** [comment]
@MwithM What do you think as maintainer? I think you are the one who would merge this PR if accepted.

**Comment by MwithM** [comment]
Wow, such a responsability.
For design it looks better, I hope it does not affect to the bisq-bot parser.

ACK

**Comment by ripcurlx** [comment]
> Wow, such a responsability. For design it looks better, I hope it does not affect to the bisq-bot parser.
> 
> ACK

Not sure if the bot takes it from the template or has some other configuration. I'll quickly check it now with my compensation request.

**Comment by ripcurlx** [comment]
Looks like it needs some changes on the bot as well. Does someone know who coded it? @jmacxx was it you?

**Comment by ghost** [comment]
Yes, I'll make a PR for the bot to handle that.

**Pull request merged**
